#!/bin/sh
#       ____  __  ______________
#      / __ \/ / / /  _/ ___/__ \
#     / / / / /_/ // / \__ \__/ /
#    / /_/ / __  // / ___/ / __/
#   /_____/_/ /_/___//____/____/
#
#   DHIS2 restore database backup

set -e

PROG=`basename $0`
BACKUPFILE=$1
DB=$2

usage() {
  echo "Usage: $PROG <backup file (tar.gz)> <dbname>"
  echo "  backup file: database dump in tar gzip format"
  echo "  dbname: the name of the database to restore"
  echo "Options:"
  echo "  -h, --help       Display this help message"
}
# Show usage if no args or -h/--help is passed
if [ "$#" -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage
  exit 0
fi

# Validate args presence
if [ -z "$BACKUPFILE" ] || [ -z "$DB" ]; then
  echo "Error: missing required arguments."
  usage
  exit 1
fi

sudo lxc exec postgres dropdb $DB
sudo lxc exec postgres -- createdb -O $DB $DB
zcat $BACKUPFILE | grep -v 'ALTER .* OWNER' | sudo lxc exec postgres -- psql $DB
echo "REASSIGN OWNED BY root TO $DB" | sudo lxc exec postgres -- psql $DB

