---
- name: Set timestamp of the backup
  ansible.builtin.set_fact:
    now: "{{ lookup('pipe', 'date +%F-%H%M-') }}"
- name: Create a backup directory
  ansible.builtin.file:
    path: /var/backups/postgres/
    mode: "0700"
    owner: postgres
    state: directory

- name: "Preparing to upgrade DHIS2, it is recommended to back up the database beforehand.\n The duration of the backup process may vary based on the size of your
    database."
  community.general.postgresql_db:
    state: dump
    name: "{{ item }}"
    target: /var/backups/postgres/{{ now }}{{ item }}.dump.gz
  become: true
  become_user: postgres
  loop: "{{ groups['instances'] }}"
