- name: Ensure prometheus-node-exporter is installed
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - prometheus-node-exporter


- name: Allow prometheus server accessing port {{ prometheus_node_port | default('9100') }}
  community.general.ufw:
    rule: allow
    port: "{{ prometheus_node_port | default('9100') }}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    comment: Allow access to prometheus_exporter from monitoring host
    state: enabled
  loop: "{{ groups['monitoring'] }}"
