---
- name: Ensure secrets directory exists
  vars:
    ansible_connection: local
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('pipe', 'id -gn') | trim }}"
  tags: [db_password_generate]
  delegate_to: 127.0.0.1
  loop:
    - "/opt/ansible/"
    - "/opt/ansible/secrets/"

- name: Ensure db_password files are owned by {{ lookup('env', 'USER') }}
  vars:
    ansible_connection: local
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('pipe', 'id -gn') | trim }}"
    mode: '0600'
  tags: [db_password_generate]
  delegate_to: 127.0.0.1
  with_fileglob:
    - /opt/ansible/secrets/*
  when: item is file

- name: Pre-requisites | {{ ansible_connection }}
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  tags: [always, sysctl-conf]
