---
# deploy war file
- name: Get sha256sum of dhis2.war file
  ansible.builtin.stat:
    path: /opt/dhis2/dhis2.war
    checksum_algorithm: sha256
  register: dhis2_war_stat

- ansible.builtin.debug:
    msg:
      - "Running release: {{ version_results.stdout | trim }}"
      - "New release: {{ patchversion_name }}"
      - set dhis2_auto_upgrade=True in your inventory file to enable automatic upgrade.
      - Prior to the upgrade, it is important to have a backup of your instance database
  when:
    - patchversion_name is defined
    - "'skipped' not in  version_results.stdout"
    - version_results.stdout | trim is version(patchversion_name, '<')  # Comparison logic

- name: Download dhis2 war file
  ansible.builtin.get_url:
    url: "{{ dhis2_url }}"
    dest: /opt/dhis2/dhis2.war
    force: true
    mode: "0640"
    # checksum: "sha256:{{ sha256 }}"
  when:
    - patchversion_name is defined
    - dhis2_url is defined
    - "'skipped' in version_results.stdout or (version_results.stdout | trim is version(patchversion_name, '<') and dhis2_auto_upgrade | default(false) | bool)"
    # - sha256 is defined

- name: Download dhis2.war with hard coded url
  ansible.builtin.get_url:
    url: "{{ dhis2_war_file }}"
    timeout: 120
    dest: /opt/dhis2/dhis2.war
    force: true
    mode: "0640"
  when: dhis2_war_file is defined and dhis2_war_file | regex_search('(https:\/\/)')

- name: Copy dhis2.war file from ansible controller
  ansible.builtin.copy:
    src: "{{ dhis2_war_file }}"
    dest: /opt/dhis2/dhis2.war
    mode: "0640"
  when: dhis2_war_file is defined and dhis2_war_file | regex_search('^(?!.*?https:\/\/).*$')

- name: Clean /var/lib/tomcat{{ tomcat_version }}/webapps
  ansible.builtin.file:
    path: /var/lib/tomcat{{ tomcat_version }}/webapps/
    state: absent
  when: "'skipped' in version_results.stdout or (patchversion_name is defined and version_results.stdout | trim is version(patchversion_name, '<') and dhis2_auto_upgrade
    | default(false) | bool ) or dhis2_war_file is defined"

- name: Creating webapps directories
  ansible.builtin.file:
    path: /var/lib/tomcat{{ tomcat_version }}/webapps/{{ dhis2_base_path | default(inventory_hostname) | to_fixed_string }}
    mode: "0755"
    state: directory
  notify: Restart Tomcat

- name: Convert javax to jakartaee  # Conversion should not happen for 2.42
  ansible.builtin.command:
    cmd: javax2jakarta /opt/dhis2/dhis2.war /opt/dhis2/jakarta-dhis2.war
    creates: /opt/dhis2/jakarta-dhis2.war
  when:
    - dhis2_war_file is undefined
    - normalized_dhis2_version is defined and normalized_dhis2_version.dhis2_version_major is  version('2.41', '<=')
    - tomcat_version == "10"

- name: Extracting jakarta-dhis2.war
  ansible.builtin.unarchive:
    src: /opt/dhis2/jakarta-dhis2.war
    dest: /var/lib/tomcat{{ tomcat_version }}/webapps/{{ dhis2_base_path | default(inventory_hostname) | to_fixed_string }}
    remote_src: true
  when:
    - dhis2_war_file is undefined
    - normalized_dhis2_version is defined and normalized_dhis2_version.dhis2_version_major is  version('2.41', '<=')
    - tomcat_version == '10'
  notify: Restart Tomcat

- name: Extracting dhis2.war file
  ansible.builtin.unarchive:
    src: /opt/dhis2/dhis2.war
    dest: /var/lib/tomcat{{ tomcat_version }}/webapps/{{ dhis2_base_path | default(inventory_hostname) | to_fixed_string }}
    remote_src: true
  when: tomcat_version != '10' or dhis2_war_file is defined and dhis2_war_file or (normalized_dhis2_version is defined and normalized_dhis2_version.dhis2_version_major is  version('2.42', '>='))
  notify: Restart Tomcat

- name: Glowroot app monitoring
  ansible.builtin.include_tasks: "{{ app_monitoring }}.yml"
  when: app_monitoring is defined

- name: Flushing handlers
  ansible.builtin.meta: flush_handlers
