---
- name: Dowload dhis2 releasese.json file
  ansible.builtin.include_tasks:
    file: dhis2-releases.yml

- name: DHIS2 instance setup with  {{ ansible_connection }}
  ansible.builtin.include_tasks:
    file: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['instances']
  tags: [always]

- name: Set dhis2 pre-install variables
  ansible.builtin.include_tasks: pre-install.yml
  when: inventory_hostname in groups['instances']
  tags: [set-dhis2-url, deploy-war, db_password_generate]

- name: Include postgresql tasks
  ansible.builtin.include_tasks: postgresql-db.yml
  when: inventory_hostname in groups['databases']

- name: Set dhis2 url, when dhis2_version is defined
  ansible.builtin.include_tasks:
    file: set-dhis2-url.yml
    apply:
      tags: [set-dhis2-url, deploy-war]
  when:
    - dhis2_war_file is undefined
    - dhis2_version is defined and dhis2_version
    - inventory_hostname in groups['instances']
  tags: [set-dhis2-url, deploy-war]

- name: Include tasks for DHIS2 tomcat setup
  ansible.builtin.include_tasks: tomcat-setup.yml
  when:
    - inventory_hostname in groups['instances']
    - (dhis2_version is defined and dhis2_version) or (dhis2_war_file is defined and dhis2_war_file)
  tags: [deploy-war]

- name: Deploy dhis2 war file
  ansible.builtin.include_tasks:
    file: deploy-war.yml
    apply:
      tags: [deploy-war]
  when:
    - inventory_hostname in groups['instances']
    - (dhis2_version is defined and dhis2_version) or (dhis2_war_file is defined and dhis2_war_file)
  tags: [deploy-war]

- name: Configuring {{ proxy }}
  ansible.builtin.include_tasks:
    file: "proxy/{{ proxy }}.yml"
    apply:
      tags:
        - proxy-conf
  when: inventory_hostname in groups['web'] and proxy is defined
  tags: [proxy-conf]

# Todo: A check to ensure this runs only when server_monitoring is munin
- name: Configuring tomcat monitoring with munin
  ansible.builtin.include_tasks:
    file: tomcat-munin-monitoring.yml
    apply:
      tags: tomcat-munin-monitoring
  tags: [tomcat-munin-monitoring]
  when:
    - server_monitoring is defined and server_monitoring == 'munin'
    - groups['monitoring']  | length > 0
    - inventory_hostname in groups['instances']
    - (dhis2_version is defined and dhis2_version) or (dhis2_war_file is defined and dhis2_war_file)

- name: Instance monitoring with Prometheus/Grafana
  ansible.builtin.include_tasks:
    file: prometheus-grafana.yml
  when:
    - server_monitoring is defined and server_monitoring in ['grafana', 'prometheus', 'grafana/prometheus']
    - groups['monitoring']  | length > 0
    - inventory_hostname in groups['instances']
