---
- name: Set timezone to {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure secrets directory exists
  vars:
    ansible_connection: local
  ansible.builtin.file:
    path: "/etc/ansible/secrets"
    state: directory
    mode: '0700'

- name: Generate database password
  ansible.builtin.set_fact:
    db_password: "{{ db_password | default(lookup('password', '/etc/ansible/secrets/' + inventory_hostname)) }}"   # psd in a file on controller
  when:
    - create_db is defined and  create_db | bool

- name: Setting tomcat verson
  ansible.builtin.set_fact:
    tomcat_version: "{{ ansible_facts['distribution_version'] | tomcat_version }}"
  tags: [set-dhis2-url, deploy-war]

- name: Check running dhis2 version
  ansible.builtin.shell:
    cmd: unzip -q -p  /var/lib/tomcat{{ tomcat_version }}/webapps/{{ dhis2_base_path | default(inventory_hostname) | to_fixed_string }}/WEB-INF/lib/dhis-service-core-*.jar build.properties | awk -F' *= *' '$1=="build.version"{print $2}'
    removes: /var/lib/tomcat{{ tomcat_version }}/webapps/{{ dhis2_base_path | default(inventory_hostname) | to_fixed_string }}/WEB-INF/lib/dhis-service-core-*.jar
  register: version_results
  changed_when: false
  tags: [set-dhis2-url, deploy-war]  #  running dhis2 instance feeds into set-url logic
