---
- name: Ensure munin-node is installed
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - munin-node
      - munin-plugins-core
      - munin-plugins-extra
      - libwww-perl
      - libxml-simple-perl

- name: Copy munin-node configuration
  ansible.builtin.template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Munin-Node

- name: Ensure munin-node is running.
  ansible.builtin.service:
    name: munin-node
    state: started
    enabled: true

- name: Open port 4949 (from munin server ) on monitored nodes
  community.general.ufw:
    rule: allow
    port: "{{ munin_node_port | default('4949') }}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    comment: Allow access from {{ item }} monitoring server
    state: enabled
  loop: "{{ groups['monitoring'] }}"

- name: Generate manager_password
  ansible.builtin.set_fact:
    manager_passwd: "{{ lookup('password', '/tmp/' + 'manager_password' + inventory_hostname, seed=inventory_hostname) }}"

# Below tasks JMX monitoring on munin
- name: Copy tomcat-users.xml file
  ansible.builtin.template:
    src: tomcat-users.xml
    dest: /etc/tomcat{{ tomcat_version | default('9') }}/tomcat-users.xml
    owner: root
    group: tomcat
    mode: '0640'

- name: Add configuration block to the file
  ansible.builtin.blockinfile:
    path: /etc/munin/plugin-conf.d/munin-node
    insertafter: EOF
    block: |
      [tomcat_*]
      env.ports 8080
      env.request /manager/status?XML=true
      env.connector "http-nio-8080"
      env.user monitor
      env.password {{ manager_passwd }}

- name: Create symlinks for Munin plugins
  ansible.builtin.file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
  loop:
    - tomcat_access
    - tomcat_jvm
    - tomcat_threads
    - tomcat_volume
  notify: Restart Munin-Node
