---
- name: Install certbot
  ansible.builtin.apt:
    name: certbot
    state: present

- name: Generate TLS/SSL Certificate with certbot
  become: true
  ansible.builtin.shell: |
    systemctl stop {{ proxy }}
    certbot certonly -n -m {{ email if email is match('^(?!.*\\.example\\.com$)[\\w\\.-]+@[\\w\\.-]+\\.\\w+$') else 'admin@' + fqdn.split('.')[-2:] | join('.') }} --agree-tos -d {{ fqdn }} --standalone --no-eff-email
  args:
    creates: /etc/letsencrypt/live/{{ fqdn }}

#  daily is identical with  0 0 * * *
- name: Add letsencrypt cronjob for cert renewal
  ansible.builtin.cron:
    cron_file: /etc/cron.d/certbot
    name: letsencrypt_renewal
    special_time: daily
    user: root
    job: certbot renew --standalone --pre-hook="service {{ proxy }} stop" --post-hook="service {{ proxy }} start"
