---
- name: Including tasks for {{ ansible_connection }}
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  when: proxy is defined and inventory_hostname in groups['web']

- name: "Installing {{ proxy }}"
  ansible.builtin.include_tasks: "{{ proxy }}-install.yml"
  when: proxy is defined and inventory_hostname in groups['web']
  tags: [nginx-perf-log]

- name: Enable munin basic Auth
  ansible.builtin.include_tasks: securing-munin.yml
  when:
    - proxy is defined
    - inventory_hostname in groups['web']
    - server_monitoring is defined
    - server_monitoring | trim == 'munin'
  tags: [securing-munin]
