---
- name: Including tasks for {{ ansible_connection }}
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['web'] and proxy is defined

- name: "Including tasks | {{ proxy }} "
  ansible.builtin.include_tasks: "{{ proxy }}.yml"
  when: inventory_hostname in groups['web'] and proxy is defined
