---
- name: Reload ufw
  connection: local
  become: true
  become_user: root
  community.general.ufw:
    state: reloaded

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true

- name: Reload Apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded
    enabled: true
