---
- name: Creating backup script
  hosts: all:!127.0.0.1
  gather_facts: false
  become: true
  tasks:
    - name: Backup Script Configuration
      ansible.builtin.include_role:
        name: backups
        tasks_from: backups.yml

