---
# handlers file for ./roles/dhis2
- name: Reload Postgres
  ansible.builtin.service:
    name: postgresql
    state: reloaded
  when:
    - database_host is defined

# stopping tomcat
- name: Stop Tomcat
  ansible.builtin.systemd:
    name: tomcat{{ tomcat_version | default('9') }}
    state: stopped
    daemon_reload: true

# starting tomcat
- name: Start Tomcat
  ansible.builtin.systemd:
    name: tomcat{{ tomcat_version | default('9') }}
    state: started
    daemon_reload: true

# restarting tomcat
- name: Restart Tomcat
  ansible.builtin.systemd:
    name: tomcat{{ tomcat_version | default('9') }}
    state: restarted
    daemon_reload: true

- name: Reload Nginx
  connection: community.general.lxd
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true

- name: Reload Apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded
    enabled: true

- name: Restart Munin-Node
  ansible.builtin.service:
    name: munin-node
    state: restarted
