---
- mame: Include {{ server_monitoring }} tasks
  ansible.builtin.include_tasks: "{{server_monitoring}}.yml"

- name: Update and Upgrade monitoring server
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 86400

- name: Set variables
  ansible.builtin.set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
    zabbix_server_apt_repository:
      - http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/
      - "{{ ansible_distribution_release }}"
      - main

- name: Downloading zabbix repo key
  ansible.builtin.get_url:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    dest: /etc/apt/keyrings/zabbix.asc
    owner: root
    group: root
    mode: "0644"
  register: zabbix_key

- name: Installing zabbix repository for {{ ansible_distribution }}
  ansible.builtin.apt_repository:
    repo: "{{ item }} [signed-by={{ zabbix_key['dest'] }}] {{ zabbix_server_apt_repository | join(' ') }}"
    state: present
    update_cache: true
  with_items:
    - deb-src
    - deb

- name: Installing zabbix-server and its dependencies
  ansible.builtin.apt:
    pkg:
      - zabbix-server-{{ zabbix_server_database }}
      - zabbix-frontend-php
      - php8.1-pgsql
      - zabbix-sql-scripts
      - zabbix-nginx-conf
      - zabbix-agent
    state: present
    update_cache: true
    cache_valid_time: 3600
    install_recommends: "{{ zabbix_server_install_recommends }}"
  register: zabbix_server_package_installed
  until: zabbix_server_package_installed is succeeded
  tags: [never]

- name: Installing the postgresql database
  ansible.builtin.include_tasks: zabbix_postgreql.yml
