---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    published_ports:
      - "0.0.0.0:8080:8080/tcp"
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_enabled: ["profile_tasks", "timer", "yaml"]
      stdout_callback: yaml
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
verifier:
  name: testinfra
  options:
    v: true
    junitxml: junit.xml
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
