---
- name: "Create integration container"
  become: true
  vars:
    ansible_connection: local
  community.general.lxd_container:
    config:
      boot.autostart.priority: "6"
      user.type: "{{ group_names[0] }}"
    name: "{{ inventory_hostname }}"
    state: started
    profiles: [default]
    ignore_volatile_options: false
    wait_for_ipv4_addresses: true
    timeout: 60
    source:
      type: image
      mode: pull
      server: "{{ lxd_source_server | default('https://cloud-images.ubuntu.com/releases') }}"
      protocol: "{{ lxd_source_protocol | default('simplestreams') }}"
      alias: "{{ guest_os }}/{{ guest_os_arch | default('amd64') }}"
    devices:
      eth0:
        type: nic
        parent: "{{ lxd_bridge_interface | default('lxdbr1') }}"
        nictype: bridged
        ipv4.address: "{{ ansible_host | ansible.utils.ipaddr(lxd_network) }}"
      root:
        path: /
        pool: "{{ lxd_storage_pool_name | default('default') }}"
        type: disk


- name: Get facts
  ansible.builtin.setup:
    gather_subset:
      - network
      - "!min"

- name: Ensuring container has configured static ip address
  become: true
  vars:
    ansible_connection: local
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    state: restarted
    wait_for_ipv4_addresses: true
  when:
    - ansible_host != ansible_facts['default_ipv4']['address']

- name: Ensure timezone is {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"
