---
- name: Checking firewall status
  become: true
  ansible.builtin.command: ufw status
  changed_when: false
  ignore_errors: true
  register: ufw_check

- name: UFW
  ansible.builtin.debug:
    msg:
      - UFW is disabled !!
      - Please enable it to continue with the setup
      - sudo ufw limit 22 # allows ssh connections to the server
      - sudo ufw enable # starts and enables ufw
  when: "'inactive' in ufw_check.stdout"

- name: End play if firewall is n not enabled
  ansible.builtin.meta: end_play
  when: "'inactive' in ufw_check.stdout"

- name: Set UFW default forward policy to ACCEPT
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/default/ufw
    regexp: ^DEFAULT_FORWARD_POLICY\=
    line: DEFAULT_FORWARD_POLICY="ACCEPT"
  notify: Reload UFW

- name: Add rules for lxd bridge
  community.general.ufw:
    rule: allow
    direction: in
    interface: "{{ lxd_bridge_interface | default('lxdbr0') }}"

- name: Configure host to NAT to the proxy container
  vars:
    ansible_connection: local
  become: true
  become_user: root
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    marker: "# {mark} NAT configuration"
    block: |
      *nat
      -F
      :PREROUTING ACCEPT [0:0]
      {% for host in groups['all'] %}
      {% if host == "proxy" %}
      -A PREROUTING -i {{ ansible_default_ipv4.interface }} -p tcp --dport 80 -j  DNAT --to-destination {{ hostvars[host]['ansible_host'] }}:80
      -A PREROUTING -i {{ ansible_default_ipv4.interface }} -p tcp --dport 443 -j  DNAT --to-destination {{ hostvars[host]['ansible_host'] }}:443
      {% endif %}
      {% endfor %}
      # setup routing
      -A POSTROUTING -s {{ lxd_network }} ! -d {{ lxd_network }} -j MASQUERADE
      COMMIT
  notify: Reload UFW
  when: proxy is defined
