---
- name: Restart Unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
