name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

      - name: Debug Release Please outputs
        run: |
          echo "PR exists: ${{ steps.release.outputs.pr != '' }}"
          echo "Release Created: ${{ steps.release.outputs.release_created }}"
          echo "PR data available: ${{ steps.release.outputs.pr != '' }}"

      - name: Prepare outputs
        id: outputs
        if: steps.release.outputs.pr != ''
        run: |
          PR_DATA='${{ steps.release.outputs.pr }}'
          echo "pr-updated=true" >> "$GITHUB_OUTPUT"
          echo "branch=$(echo "$PR_DATA" | jq -r .headBranchName)" >> "$GITHUB_OUTPUT"
          echo "version=$(echo "$PR_DATA" | jq -r .title | sed 's/.*: release \(.*\)/\1/')" >> "$GITHUB_OUTPUT"

    outputs:
      pr-updated: ${{ steps.outputs.outputs.pr-updated }}
      branch: ${{ steps.outputs.outputs.branch }}
      version: ${{ steps.outputs.outputs.version }}